### ISSUE TITLE
Default headers?

### ISSUE THREAD

**Issue by spencerjsmall** [gaetansenn/vue-api#1]
Hey! Super pumped on trying out this library. I'm wondering if it's possible, either globally or through the `useFetchModel` composable, to set default headers (such as authorization, etc.). Thanks! For context, I'm building with Nuxt 3.

**Comment by gaetansenn** [comment]
Hi there,

I'm glad that you want to use my library for your Nuxt 3 project. Since useFetchModel uses the ofetch library (https://github.com/unjs/ofetch and https://nuxt.com/docs/api/composables/use-fetch), you can easily set it up like this:

```ts
File: _utils.ts

export function getEcomFetchOption(): Partial<FetchOptions> {
  const { loggedIn } = useUserSession()
  const { locale } = useI18n()
  const { $configuration } = useNuxtApp()
  const config = useRuntimeConfig()

  return {
    baseURL: config.public.apiBaseUrl,
    onRequest: (context) => {

      context.options.headers = {
        ...(context.options.headers || {}),
        'Accept-Language': locale.value,
        'Custom-Header': 'Custom value'
      }
    }
  }
}
 ```
 
For example, this method is then used in all the composables in the API folder where I need custom headers.

Example of usage:

```ts
export default function () {
  const { useFetch } = useFetchModel(getEcomFetchOption())

  return {
    findById: async (id: number) => {
      const response = await useFetch.get<Product>(`/products/${id}`, {
        key: `ecom-product-${id}`
      })

      if (response.error.value) {
        throw showError({
          statusCode: 404,
          statusMessage: response.error.value.statusMessage,
          message: response.error.value.message
        })
      }

      return response
    }
  }
}
```
 
 Don't hesitate to add a star ;)

**Comment by spencerjsmall** [comment]
Thank you! Exactly what i needed.

**Comment by spencerjsmall** [comment]
@gaetansenn I have one related question here... I want to pass `credentials` (cookies) with server-side `useFetch` requests, which should be possible if this library uses `useRequestFetch` under the hood, according to [these docs](https://nuxt.com/docs/getting-started/data-fetching#passing-headers-and-cookies). However, it appears cookies are not being passed on the server side if I set `credentials: 'include'`. Any guidance here?

**Comment by gaetansenn** [comment]
Hello @spencerjsmall normally useFetch will automatically forward the cookie to the requested server if it's in the same domain name policy of your cookie. If you want to be sure that it's not related to my library you can test it directly using `useFetch` from nuxt.
