### ISSUE TITLE
Nuxt: useTransform does not auto-import

### ISSUE THREAD

**Issue by spencerjsmall** [gaetansenn/vue-api#2]
Just a note here - the useTransform composable does not seem to autoimport into api definitions in my Nuxt app, nor can i seem to import it manually.

**Comment by spencerjsmall** [comment]
Also, it appears as though `format: 'camelCase'` when passed as a top level option just removes an underscore and doesn't actually format as camelCase.
For example "first_name" -> "firstname".
In the meantime, I'm using a custom mapping function to achieve this:
```
mapping: ({ model }: { model: { data: { [key: string]: any } } }) => {
  return Object.entries(model.data).reduce(
    (acc, [key, value]) => {
      const camelKey = key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase())
      acc[camelKey] = value
      return acc
    },
    {} as { [key: string]: any },
  )
},
```

**Comment by gaetansenn** [comment]
Hi @spencerjsmall, sorry for the delay! I've been overwhelmed with work. I'll take a look if I find the time, but if you're motivated, feel free to submit a PR. 😉

**Comment by gaetansenn** [comment]
For the useTransform I have exported it from @vue-api/core. So you can import it like

```ts
import { useTransform } from '@vue-api/core'
```
